# Google Analytics configuration
analytics: 
  google: 
    id: G-G0P6TJYH2C

# Site description with HTML formatting
description: >
  <br>
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/vcalefi/">
    <span class="material-icons">linkedin</span>
  </a>

# Language setting for the site
lang: en-US

# Path to the site logo
logo: "/images/logo.png?raw=true"

# List of Jekyll plugins to use
plugins:
- jekyll-remote-theme

# Remote theme configuration
remote_theme: pages-themes/minimal@v0.2.0

# Site title
title: Victor Calefi

# Base URL of the site
url: https://vcramos.github.io